version: '3.8'

services:
  gemini-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    image: gemini-proxy:latest
    container_name: gemini-proxy
    restart: unless-stopped

    ports:
      - "8000:8000"

    volumes:
      # Mount configuration files (REQUIRED)
      - ./proxy.yaml:/app/proxy.yaml:ro
      - ./keys.yaml:/app/keys.yaml:ro

      # Persistence for key health state and runtime data
      - ./.runtime:/app/.runtime

    healthcheck:
      test: ["CMD", "bun", "-e", "await fetch('http://localhost:8000/health').then(r => r.ok ? process.exit(0) : process.exit(1))"]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3

    # Resource limits (optional, adjust based on your needs)
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M

    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    # Security options
    security_opt:
      - no-new-privileges:true

    # Run as non-root user
    user: "bun"

# Optional: Create named volume for better persistence
volumes:
  gemini-proxy-data:
    driver: local

# Optional: Custom network
networks:
  default:
    name: gemini-proxy-network
