proxy:
  host: "0.0.0.0"
  port: 8000
  adminToken: "test-admin-token"
  requestTimeoutMs: 10000
  upstreamBaseUrl: "https://generativelanguage.googleapis.com"
  accessTokens: []
  requireAuth: false

monitoring:
  healthCheckIntervalSeconds: 30
  failureThreshold: 3
  recoveryTimeSeconds: 300
  windowSeconds: 300

persistence:
  sqlitePath: ".runtime/state.sqlite"
  fallbackJsonPath: ".runtime/state.json"
